server:
  AppVersion: 1.0.0
  Port: :8080
  PprofPort: :5555
  Mode: production
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

redis:
  RedisAddr: keydb-service:6379
  RedisPassword: yourpassword
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: yourpassword
  DB: 0


services:
  OtididaeURL: http://otididae-video-service/send_binary_data_celery

mongodb:
  MongoURI: mongodb://root:example@mongodb-service:27017